### ISSUE TITLE
Stuck at "initializing widgets"

### ISSUE THREAD

**Issue by ketch** [SamLau95/nbinteract#123]
I've followed the tutorial to try to create an interactive HTML version of a notebook.  The result is here:

https://ketch.github.io/covid-blog-posts/01_SIR_Model.html

However, when I try to load the widgets, the message "initializing widgets" appears and then nothing else happens.  I've waited for several minutes.

**Comment by SamLau95** [comment]
Try running the notebook, then saving without clearing outputs. nbinteract detects where to place widgets by looking at the cell outputs.

**Comment by ketch** [comment]
Thanks, and sorry for not reading the docs!  It works now.
