### ISSUE TITLE
Automatically load the widgets

### ISSUE THREAD

**Issue by MuriloHMoreira** [SamLau95/nbinteract#151]
Hello!
FIrst things first, thanks for the awesome package!
I was trying to use it for some webpages for students to interact with the lessons, and one idea was to try to automatically show the widgets. Is there a way?
Thank you very much!

**Comment by SamLau95** [comment]
I originally had the widgets automatically show, but for popular pages this caused excessive load on the Binder servers (which I consider a public good). I won't re-implement automatically showing widgets unless the Binder people say we can.

**Comment by MuriloHMoreira** [comment]
Oh you are right, I did not think about this!
Sorry and thanks for the explanation.
All the best,
Murilo
