### ISSUE TITLE
Write nbi.scatter

### ISSUE THREAD

**Issue by SamLau95** [SamLau95/nbinteract#18]
We currently have an `nbi.scatter_drag` method which creates a scatterplot with draggable points.

However, this doesn't work super well when generating points using functions. For example:

```python
>>> def x(): return np.arange(10)
>>> def y(xs): return xs + 10

>>> scatter_drag(x, y) # Dragging points conflicts with function outputs
```

We should instead have an `nbi.scatter` function that doesn't allow point dragging but takes in response functions like the other plotting functions:

```python
>>> def x(n): return np.random.normal(n)
>>> def y(xs): return np.random.normal(len(xs))
>>> scatter(x, y, n=100)
interactive(...)
```

**Comment by Calebs97** [comment]
#22 added
