### ISSUE TITLE
mybinder.org usage

### ISSUE THREAD

**Issue by betatim** [SamLau95/nbinteract#33]
Hello from mybinder.org :) Just wanted to stop by and say that I like nbinteract! 

You are by far the biggest user of mybinder.org by number of pods launched. Once in a while we will get about ~350 or so pods related to nbinteract appear all in oen go and then slowly die away again over time. I was wondering if you knew what that could be.

This is what it looks like on grafana.mybinder.org 
![image](https://user-images.githubusercontent.com/1448859/35828769-0af68e10-0ac1-11e8-8b07-e9996c9b5604.png)

**Comment by betatim** [comment]
It looks like nbinteract is also used for https://www.textbook.ds100.org/ and makes a request to mybinder.org each time someone loads the page. This means each visitor spawns a new binder. As far as I can tell that binder is re-used for that visitor. Right now there are 221 pods related to the ds100 textbook running. Could you adjust nbinteract so that it only makes a request when the user explicitly clicks a button to make the page interactive?

Right now the nbinteract behaviour leads to us having to scale up the mybinder cluster a lot (which costs $$$) and presumably most of the nbinteract related binders are just idling. So requiring a click would be good to keep the load lower.

**Comment by minrk** [comment]
And we will soon limit the number of concurrent users for a given repo, so this will probably start failing to get Binders if it's requesting more than it needs.

**Comment by betatim** [comment]
Related mybinder issue https://github.com/jupyterhub/binder/issues/34. Maybe close this?

**Comment by SamLau95** [comment]
Discussion moved to #34 !
