### ISSUE TITLE
short_answer notebook: TypeError: multiple_choice() got an unexpected keyword argument 'answer_list'

### ISSUE THREAD

**Issue by pleabargain** [SamLau95/nbinteract#70]
`nb.multiple_choice(question="What is 1+1?", answer_list=['1', '2', '3'], correct_answer = '2')
`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-05f0b41965a4> in <module>()
----> 1 nb.multiple_choice(question="What is 1+1?", answer_list=['1', '2', '3'], correct_answer = '2')

TypeError: multiple_choice() got an unexpected keyword argument 'answer_list'

**Comment by SamLau95** [comment]
@Calebs97 Think you can take look at this? We might not have updated the docs to match some API changes.

**Comment by Calebs97** [comment]
I believe the docs have already been updated. https://www.nbinteract.com/recipes/recipes_interactive_questions.html
