### ISSUE TITLE
Heavy mybinder.org load

### ISSUE THREAD

**Issue by betatim** [SamLau95/nbinteract#72]
Hi guys,

you are too popular :) This morning we noticed quite a lot of load on mybinder.org and tracked it down to nbinteract.

We track the number of binders launched (in a 10m window), which is plotted here:
https://grafana.mybinder.org/dashboard/db/1-overview?refresh=1m&orgId=1&panelId=17&fullscreen&from=1523872922006&to=1523916122006 basically all of that is nbinteract (after about 6pm Zurich time)

What seems to cause a lot of load for us isn't so much the total number of binders connected to nbinteract but the fact that you are launching a lot of them. Could you implement something that reuses a running binder when a user clicks on a different page or something?

@choldgraf @willingc

**Comment by betatim** [comment]
We just lowered the per repo limit from 200 to 100 to see if this will help us cope better with the load and increase the pod launch success rate.

Right now there are about 150 nbinteract binders running.

https://github.com/jupyterhub/mybinder.org-deploy/pull/556

**Comment by cwilling** [comment]
An email of your initial "too popular" comment was sent to user cwilling as well as (or instead of) to user willingc. Maybe that was a typo (since edited), otherwise an interesting bug in the infrastructure.

**Comment by SamLau95** [comment]
Looks like the traffic spike went away after banning for a bit. @choldgraf and I think this might be related to https://github.com/jupyterhub/binderhub/issues/317 but we haven't pinned the exact issue down.
