### ISSUE TITLE
relax requirement ipywidgets<7.2 for ipywidgets 7.2.1

### ISSUE THREAD

**Issue by pleabargain** [SamLau95/nbinteract#73]
on latest update for pip3 (python 3.5) I'm getting
`nbinteract 0.1.8 has requirement ipywidgets<7.2,>=7, but you'll have ipywidgets 7.2.1 which is incompatible.`
Maybe relax the requirement for ipywidgets7.2.1?

**Comment by SamLau95** [comment]
That sounds reasonable to me—thanks for bringing this up.
