### ISSUE TITLE
Binder error web page publish - "Could not resolve ref for gh. . ."

### ISSUE THREAD

**Issue by SantiagoG** [SamLau95/nbinteract#99]
"""""""
Windows 7, behind a proxy
Running tutorial straight from http://mybinder.org/
""""""""

Followed your tutorial steps:

https://www.nbinteract.com/tutorial/tutorial_intro.html

I created a public repo: https://github.com/SantiagoG/nbinteract-test

Initializing nbinteract (Binder terminal):

`jovyan@jupyter-santiagog-2dnbinteract-2dtest-2dhjwtpv4i:~$ nbinteract init

[nbinteract] Initializing folder for nbinteract.
[nbinteract]
[nbinteract] Checking to see if this folder is the root folder of a git project.
[nbinteract] Looks like we're in the root of a git project.
[nbinteract]
[nbinteract] Checking for requirements.txt or Dockerfile.
[nbinteract] requirements.txt found.
[nbinteract]
[nbinteract] Generating .nbinteract.json file...
[nbinteract] Created .nbinteract.json file successfully
[nbinteract]
[nbinteract] Initialization complete! Now, you should make a git commit with the
[nbinteract]   files created by in this process and push your commits to GitHub.
[nbinteract]
[nbinteract] After you push, you should visit
[nbinteract]   https://mybinder.org/v2/gh/nbinteract/test/master and verify that
[nbinteract]   your Binder image successfully starts.
`

When clicking binder link I get: 

`Could not resolve ref for gh:nbinteract/test/master. Double check your URL.`

Also stuck at your web page publishing steps. Widgets fail to load after following publishing steps in Github Pages:

tutorial steps: https://www.nbinteract.com/tutorial/tutorial_publishing.html

SantiagoG.github.io/nbinteract-test/tutorial.html

![image](https://user-images.githubusercontent.com/3590838/49493189-d1a04000-f8a6-11e8-9de4-912dca9d10e5.png)

Thanks much!

**Comment by SamLau95** [comment]
Thanks for the report. I took a look at your Binder server and confirmed that there's a bug in the initialization script.

Currently, your `.nbinteract.json` file has the following content:

```json
{
    "spec": "nbinteract/test/master"
}
```

You should change it to read:

```json
{
    "spec": "SantiagoG/nbinteract-test/master"
}
```

I'll push a fix for this issue so others won't have to do this.
